#+TITLE:     Notes on Real Analysis
#+DATE:
#+AUTHOR:
#+OPTIONS: toc:nil

* Foundations
** Postulates
*** Numbers
**** *Real Numbers as a Field*

   1. *Associativity*

      $\forall a,b,c \in \Re: a+(b+c)=(a+b)+c$

      /Exercise 1/:

      Prove that the sums of an arbitrary number of equivalent variables in an immutable sequence are equal up to the placement of parentheses.

      /Exercise 2/:

      Let the immutable sequence written in such a form that there are no two elements not parenthesised be called a /nested/ sequence.

      For example, $((a+b)+c)+d$ and $(a+b)+(c+d)$ are both nested sequences.

      How many different nested sequences can be written from a sequence of n letters?

   2. *Commutativity of Addition*

      $\forall \ a, b \in \Re: a+b=b+a$

   3. *Commutativity of Multiplication*

      $\forall \ a, b \in \Re: a \times b=b \times a$

   4. *Existence of an Additive Identity*

      $\exists \ 0\in \Re\ \forall a \in \Re: a+0=a$

   5. *Existence of a Multiplicative Identity*

      $\exists \ 1\in\Re\ \forall a \in \Re: a\times 1=a$

   6. *Existence of an Additive Inverse*

      $\forall \ a\in\Re\ \exists -a: a+(-a)=0$

   7. *Existence of a Multiplicative Inverse*

      $\forall \ a\in\Re\ \exists\ a^{-1}: a\times a^{-1}=1$

   8. *Distributivity*

      $\forall \ a,b,c \in \Re: a\times(b+c)=a\times b+a\times c$
**** *Real Numbers as an Ordered Field*

   Let $P$ be the set of positive numbers.

   Let the binary operator $>$ be defined so that $\forall \ a,b \in \Re: a > b \iff a-b\in P$.

   Similarly,  $\forall \ a,b \in \Re: a < b \iff b-a\in P$.

   9. [@9] *Trichotomy Law*

      $\forall \ a \in \Re$ one and only one of the following holds:

      - $a=0$

      - $a \in P$

      - $a \not\in P$

   10.
